version: "3.9"

services:
   db:
     image: postgres:16
     container_name: postgres-db
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: backend_db
     ports:
      - "5432:5432"

   api:
     build: .
     container_name: fastapi_app
     ports:
       - "8000:8000"
     depends_on:
      - db
